//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FingerValidator.Registraduria_8180 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchCandidate", Namespace="http://www.morpho.com/replicat/xsd/1.0")]
    [System.SerializableAttribute()]
    public partial class SearchCandidate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string m_s_NUTField;
        
        private string m_s_OperatorIdField;
        
        private string m_s_ClientIdField;
        
        private string m_s_NuipNipField;
        
        private string m_fpf_FingerPrintFormatField;
        
        private FingerValidator.Registraduria_8180.SearchCandidate.mv_fi_FingersToGetType mv_fi_FingersToGetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string m_s_NUT {
            get {
                return this.m_s_NUTField;
            }
            set {
                if ((object.ReferenceEquals(this.m_s_NUTField, value) != true)) {
                    this.m_s_NUTField = value;
                    this.RaisePropertyChanged("m_s_NUT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string m_s_OperatorId {
            get {
                return this.m_s_OperatorIdField;
            }
            set {
                if ((object.ReferenceEquals(this.m_s_OperatorIdField, value) != true)) {
                    this.m_s_OperatorIdField = value;
                    this.RaisePropertyChanged("m_s_OperatorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string m_s_ClientId {
            get {
                return this.m_s_ClientIdField;
            }
            set {
                if ((object.ReferenceEquals(this.m_s_ClientIdField, value) != true)) {
                    this.m_s_ClientIdField = value;
                    this.RaisePropertyChanged("m_s_ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string m_s_NuipNip {
            get {
                return this.m_s_NuipNipField;
            }
            set {
                if ((object.ReferenceEquals(this.m_s_NuipNipField, value) != true)) {
                    this.m_s_NuipNipField = value;
                    this.RaisePropertyChanged("m_s_NuipNip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string m_fpf_FingerPrintFormat {
            get {
                return this.m_fpf_FingerPrintFormatField;
            }
            set {
                if ((object.ReferenceEquals(this.m_fpf_FingerPrintFormatField, value) != true)) {
                    this.m_fpf_FingerPrintFormatField = value;
                    this.RaisePropertyChanged("m_fpf_FingerPrintFormat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=5)]
        public FingerValidator.Registraduria_8180.SearchCandidate.mv_fi_FingersToGetType mv_fi_FingersToGet {
            get {
                return this.mv_fi_FingersToGetField;
            }
            set {
                if ((object.ReferenceEquals(this.mv_fi_FingersToGetField, value) != true)) {
                    this.mv_fi_FingersToGetField = value;
                    this.RaisePropertyChanged("mv_fi_FingersToGet");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.CollectionDataContractAttribute(Name="SearchCandidate.mv_fi_FingersToGetType", Namespace="http://www.morpho.com/replicat/xsd/1.0", ItemName="mv_b_FingerPrintData")]
        [System.SerializableAttribute()]
        public class mv_fi_FingersToGetType : System.Collections.Generic.List<string> {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="searchCandidateResponse", Namespace="http://www.morpho.com/replicat/xsd/1.0")]
    [System.SerializableAttribute()]
    public partial class searchCandidateResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string m_ss_SearchStatusField;
        
        private string m_s_NUTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string m_s_RequestIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string m_s_OperatorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string m_s_ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string m_s_NuipNipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FingerValidator.Registraduria_8180.searchCandidateResponse.CandidateAlphaType CandidateAlphaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FingerValidator.Registraduria_8180.searchCandidateResponse.FingerPrintDataType FingerPrintDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string m_ss_SearchStatus {
            get {
                return this.m_ss_SearchStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.m_ss_SearchStatusField, value) != true)) {
                    this.m_ss_SearchStatusField = value;
                    this.RaisePropertyChanged("m_ss_SearchStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string m_s_NUT {
            get {
                return this.m_s_NUTField;
            }
            set {
                if ((object.ReferenceEquals(this.m_s_NUTField, value) != true)) {
                    this.m_s_NUTField = value;
                    this.RaisePropertyChanged("m_s_NUT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string m_s_RequestId {
            get {
                return this.m_s_RequestIdField;
            }
            set {
                if ((object.ReferenceEquals(this.m_s_RequestIdField, value) != true)) {
                    this.m_s_RequestIdField = value;
                    this.RaisePropertyChanged("m_s_RequestId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string m_s_OperatorId {
            get {
                return this.m_s_OperatorIdField;
            }
            set {
                if ((object.ReferenceEquals(this.m_s_OperatorIdField, value) != true)) {
                    this.m_s_OperatorIdField = value;
                    this.RaisePropertyChanged("m_s_OperatorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string m_s_ClientId {
            get {
                return this.m_s_ClientIdField;
            }
            set {
                if ((object.ReferenceEquals(this.m_s_ClientIdField, value) != true)) {
                    this.m_s_ClientIdField = value;
                    this.RaisePropertyChanged("m_s_ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string m_s_NuipNip {
            get {
                return this.m_s_NuipNipField;
            }
            set {
                if ((object.ReferenceEquals(this.m_s_NuipNipField, value) != true)) {
                    this.m_s_NuipNipField = value;
                    this.RaisePropertyChanged("m_s_NuipNip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public FingerValidator.Registraduria_8180.searchCandidateResponse.CandidateAlphaType CandidateAlpha {
            get {
                return this.CandidateAlphaField;
            }
            set {
                if ((object.ReferenceEquals(this.CandidateAlphaField, value) != true)) {
                    this.CandidateAlphaField = value;
                    this.RaisePropertyChanged("CandidateAlpha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public FingerValidator.Registraduria_8180.searchCandidateResponse.FingerPrintDataType FingerPrintData {
            get {
                return this.FingerPrintDataField;
            }
            set {
                if ((object.ReferenceEquals(this.FingerPrintDataField, value) != true)) {
                    this.FingerPrintDataField = value;
                    this.RaisePropertyChanged("FingerPrintData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.CollectionDataContractAttribute(Name="searchCandidateResponse.CandidateAlphaType", Namespace="http://www.morpho.com/replicat/xsd/1.0", ItemName="mv_ca_AlphaValues")]
        [System.SerializableAttribute()]
        public class CandidateAlphaType : System.Collections.Generic.List<FingerValidator.Registraduria_8180.mv_ca_AlphaValues> {
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.CollectionDataContractAttribute(Name="searchCandidateResponse.FingerPrintDataType", Namespace="http://www.morpho.com/replicat/xsd/1.0", ItemName="mv_fpd_FingerPrintsData")]
        [System.SerializableAttribute()]
        public class FingerPrintDataType : System.Collections.Generic.List<FingerValidator.Registraduria_8180.mv_fpd_FingerPrintsData> {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="mv_ca_AlphaValues", Namespace="http://www.morpho.com/replicat/xsd/1.0")]
    [System.SerializableAttribute()]
    public partial class mv_ca_AlphaValues : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string m_ai_AlphaIdField;
        
        private string m_s_AlphaValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string m_ai_AlphaId {
            get {
                return this.m_ai_AlphaIdField;
            }
            set {
                if ((object.ReferenceEquals(this.m_ai_AlphaIdField, value) != true)) {
                    this.m_ai_AlphaIdField = value;
                    this.RaisePropertyChanged("m_ai_AlphaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string m_s_AlphaValue {
            get {
                return this.m_s_AlphaValueField;
            }
            set {
                if ((object.ReferenceEquals(this.m_s_AlphaValueField, value) != true)) {
                    this.m_s_AlphaValueField = value;
                    this.RaisePropertyChanged("m_s_AlphaValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="mv_fpd_FingerPrintsData", Namespace="http://www.morpho.com/replicat/xsd/1.0")]
    [System.SerializableAttribute()]
    public partial class mv_fpd_FingerPrintsData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string m_fi_FingerIdField;
        
        private string m_fpf_FingerPrintFormatField;
        
        private byte[] mv_b_FingerPrintDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string m_fi_FingerId {
            get {
                return this.m_fi_FingerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.m_fi_FingerIdField, value) != true)) {
                    this.m_fi_FingerIdField = value;
                    this.RaisePropertyChanged("m_fi_FingerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string m_fpf_FingerPrintFormat {
            get {
                return this.m_fpf_FingerPrintFormatField;
            }
            set {
                if ((object.ReferenceEquals(this.m_fpf_FingerPrintFormatField, value) != true)) {
                    this.m_fpf_FingerPrintFormatField = value;
                    this.RaisePropertyChanged("m_fpf_FingerPrintFormat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public byte[] mv_b_FingerPrintData {
            get {
                return this.mv_b_FingerPrintDataField;
            }
            set {
                if ((object.ReferenceEquals(this.mv_b_FingerPrintDataField, value) != true)) {
                    this.mv_b_FingerPrintDataField = value;
                    this.RaisePropertyChanged("mv_b_FingerPrintData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.morpho.com/replicat/wsdl/1.0", ConfigurationName="Registraduria_8180.IReplicat")]
    public interface IReplicat {
        
        // CODEGEN: Generating message contract since the operation SearchCandidate is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        FingerValidator.Registraduria_8180.SearchCandidateResponse1 SearchCandidate(FingerValidator.Registraduria_8180.SearchCandidate1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<FingerValidator.Registraduria_8180.SearchCandidateResponse1> SearchCandidateAsync(FingerValidator.Registraduria_8180.SearchCandidate1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchCandidate1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.morpho.com/replicat/wsdl/1.0", Order=0)]
        public FingerValidator.Registraduria_8180.SearchCandidate SearchCandidate;
        
        public SearchCandidate1() {
        }
        
        public SearchCandidate1(FingerValidator.Registraduria_8180.SearchCandidate SearchCandidate) {
            this.SearchCandidate = SearchCandidate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchCandidateResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.morpho.com/replicat/wsdl/1.0", Order=0)]
        public FingerValidator.Registraduria_8180.searchCandidateResponse SearchCandidateResponse;
        
        public SearchCandidateResponse1() {
        }
        
        public SearchCandidateResponse1(FingerValidator.Registraduria_8180.searchCandidateResponse SearchCandidateResponse) {
            this.SearchCandidateResponse = SearchCandidateResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReplicatChannel : FingerValidator.Registraduria_8180.IReplicat, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReplicatClient : System.ServiceModel.ClientBase<FingerValidator.Registraduria_8180.IReplicat>, FingerValidator.Registraduria_8180.IReplicat {
        
        public ReplicatClient() {
        }
        
        public ReplicatClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReplicatClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReplicatClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReplicatClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FingerValidator.Registraduria_8180.SearchCandidateResponse1 FingerValidator.Registraduria_8180.IReplicat.SearchCandidate(FingerValidator.Registraduria_8180.SearchCandidate1 request) {
            return base.Channel.SearchCandidate(request);
        }
        
        public FingerValidator.Registraduria_8180.searchCandidateResponse SearchCandidate(FingerValidator.Registraduria_8180.SearchCandidate SearchCandidate1) {
            FingerValidator.Registraduria_8180.SearchCandidate1 inValue = new FingerValidator.Registraduria_8180.SearchCandidate1();
            inValue.SearchCandidate = SearchCandidate1;
            FingerValidator.Registraduria_8180.SearchCandidateResponse1 retVal = ((FingerValidator.Registraduria_8180.IReplicat)(this)).SearchCandidate(inValue);
            return retVal.SearchCandidateResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FingerValidator.Registraduria_8180.SearchCandidateResponse1> FingerValidator.Registraduria_8180.IReplicat.SearchCandidateAsync(FingerValidator.Registraduria_8180.SearchCandidate1 request) {
            return base.Channel.SearchCandidateAsync(request);
        }
        
        public System.Threading.Tasks.Task<FingerValidator.Registraduria_8180.SearchCandidateResponse1> SearchCandidateAsync(FingerValidator.Registraduria_8180.SearchCandidate SearchCandidate) {
            FingerValidator.Registraduria_8180.SearchCandidate1 inValue = new FingerValidator.Registraduria_8180.SearchCandidate1();
            inValue.SearchCandidate = SearchCandidate;
            return ((FingerValidator.Registraduria_8180.IReplicat)(this)).SearchCandidateAsync(inValue);
        }
    }
}
